# First stage: build the Symfony application and install all dependencies.
FROM php:8.3-fpm AS builder

# Set the working directory inside the container.
WORKDIR /app

# Install system packages needed for Symfony and Composer.
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    curl \
    nodejs \
    npm \
    && docker-php-ext-install pdo pdo_mysql \
    && rm -rf /var/lib/apt/lists/*

# Install Composer globally.
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Allow Composer to run as root user.
ENV COMPOSER_ALLOW_SUPERUSER=1

# Copy Composer files first for Docker cache optimization.
COPY composer.json composer.lock ./

# Install Symfony PHP dependencies.
RUN composer install --no-interaction --no-scripts --optimize-autoloader

# Copy the entire Symfony project into the container.
COPY . .

# Do not bake .env with localhost DATABASE_URL — Railway injects variables at runtime.

# Optimize Composer autoload files for production.
RUN composer install --no-interaction --optimize-autoloader --no-ansi || true

# Install frontend importmap assets.
RUN php bin/console importmap:install --no-interaction

# Warm up Symfony cache for faster performance.
RUN php bin/console cache:warmup --env=prod --no-debug || true


FROM php:8.3-fpm AS runtime

# Set the working directory inside the runtime container.
WORKDIR /app

# Install Nginx web server.
RUN apt-get update && apt-get install -y \
    nginx \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Copy the prepared application from the builder stage.
COPY --from=builder /app /app

# 1. Safely extract ONLY the extension configurations generated by docker-php-ext-install
COPY --from=builder /usr/local/etc/php/conf.d/ /usr/local/etc/php/conf.d/
COPY --from=builder /usr/local/lib/php/extensions/ /usr/local/lib/php/extensions/
# 2. Extract the directory containing the actual compiled shared object (*.so) binaries
COPY --from=builder /usr/local/lib/php/extensions /usr/local/lib/php/extensions

# Configure permissions for Symfony runtime folders.
RUN mkdir -p /app/var && \
    chown -R www-data:www-data /app && \
    chmod -R 755 /app && \
    chmod -R 775 /app/var

# Configure Nginx for Symfony.
COPY nginx-main.conf /etc/nginx/nginx.conf

# Remove default nginx site configs and add the Symfony site configuration.
RUN rm -rf /etc/nginx/conf.d/* /etc/nginx/sites-enabled /etc/nginx/sites-available
COPY nginx.conf.template /etc/nginx/conf.d/symfony.conf.template

# Configure Nginx for Symfony.
COPY entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh \
    && chmod +x bin/railway-jwt-keys.sh bin/railway-migrate.sh bin/railway-start.sh

# Healthcheck uses Railway $PORT at runtime (entrypoint writes nginx config first).
HEALTHCHECK --interval=30s --timeout=5s --start-period=120s --retries=3 \
    CMD sh -c 'curl -f "http://127.0.0.1:${PORT:-8080}/health" || exit 1'

EXPOSE 8080

# Start the container using the custom entrypoint.
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]